logging:
  level:
    br.com.estado: ${API_LOG_LEVEL:DEBUG}
    org.springframework:
      boot.context: INFO

server:
  compression:
    enabled: true
  context-path: /

documentation:
  info:
    title: Api Estado
    description: Gerenciamento Estados e municípios.
  version: ~project.version~
  base-package: br.com.state.controller

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  cache:
    type: redis
  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:state}?createDatabaseIfNotExist=true&reconnect=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    tomcat:
      test-on-borrow: true
      test-on-connect: true
      validation-query: SELECT 1 FROM DUAL
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none

api:
  dollar-currency: https://free.currconv.com/api/v7/convert

app:
  homepage: index.html
  cost:
    cost-per-citizen-in-dollar: 123.45
    discount-above: 50000
    discount-value: 12.3
