logging:
  level:
    br.com.estado: ${API_LOG_LEVEL:DEBUG}
    org.springframework:
      boot.context: INFO

server:
  compression:
    enabled: true
  context-path: /
  port: ${SERVER_PORT:8000}

documentation:
  info:
    title: Api Estado
    description: Gerenciamento Estados e municípios.
  version: ~project.version~
  base-package: br.com.state.controller

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  cache:
    type: redis
  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticket?createDatabaseIfNotExist=true&reconnect=true
    username: root
    password: db1234567
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:state}?createDatabaseIfNotExist=true&reconnect=true
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
    tomcat:
      test-on-borrow: true
      test-on-connect: true
      validation-query: SELECT 1 FROM DUAL
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none

api:
  dolar: https://api-dolar

app:
  homepage: index.html
