/**
 * Api Estado
 * Gerenciamento Estados e municípios.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CityDto } from './cityDto';


export interface CityListResponse { 
    /**
     * City list
     */
    cities?: Array<CityDto>;
    /**
     * Total of cities
     */
    totalElements?: number;
}
