/**
 * Api Estado
 * Gerenciamento Estados e municípios.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StateDto { 
    /**
     * State code
     */
    code?: string;
    /**
     * Flag url
     */
    flagUrl?: string;
    /**
     * State id
     */
    id?: number;
    /**
     * State name
     */
    name?: string;
    /**
     * Population
     */
    population?: number;
    /**
     * Population cost
     */
    populationCost?: number;
}
